# Truth Table Neural Net

In [4]:
## Import package

import tensorflow as tf

In [5]:
## Define data

x = [[False,False],[False,True],[True,False],[True,True]]
y = [False,True,True,False]

In [7]:
## OHE the data

x = tf.keras.utils.to_categorical(x, num_classes=2)
print(x,'\n')
y = tf.keras.utils.to_categorical(y, num_classes=2)
print(y)

[[[[0. 1.]
   [1. 0.]]

  [[0. 1.]
   [1. 0.]]]


 [[[0. 1.]
   [1. 0.]]

  [[1. 0.]
   [0. 1.]]]


 [[[1. 0.]
   [0. 1.]]

  [[0. 1.]
   [1. 0.]]]


 [[[1. 0.]
   [0. 1.]]

  [[1. 0.]
   [0. 1.]]]] 

[[1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]]


In [ ]:
## Define model

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.RNN(10))
model.add(tf.keras.layers.Dense(4, activation='relu'))
model.add(tf.keras.layers.Dense(1, activation = 'sigmoid'))

sgd = tf.keras.optimizers.SGD(lr=0.0001)

## Compile model with metrics
model.compile(optimizer=sgd, loss='binary_crossentropy', metrics=['accuracy'])
model.summary()


In [171]:
%%capture

## Train the model
hist = model.fit(x,y, epochs=500, verbose=2)

In [177]:
print("Loss:\n", hist.history['loss'][-1])
print("Accuracy:\n", hist.history['accuracy'][-1])
print("\nPrediction:\n",model.predict(x))
print("\nClasses:\n",model.predict_classes(x)[:,1])

Loss:
 0.6934748888015747
Accuracy:
 0.5

Prediction:
 [[[0.48190063]
  [0.48190063]]

 [[0.48190063]
  [0.5003518 ]]

 [[0.5003518 ]
  [0.48190063]]

 [[0.5003518 ]
  [0.5003518 ]]]

Classes:
 [[0]
 [1]
 [0]
 [1]]


In [ ]:
import tensorflow as tf

T, F = 1.00001, -1.00001
bias = 1.00001
train_in = [
    [T, T, bias],
    [T, F, bias],
    [F, T, bias],
    [F, F, bias],
]
train_out = [
    [T],
    [F],
    [F],
    [F],
]
w = tf.Variable(tf.random.normal([3, 1]))
# step(x) = { 1 if x > 0; -1 otherwise }
def step(x):
    is_greater = tf.greater(x, 0)
    as_float = tf.dtypes.cast(is_greater, tf.float32)
    doubled = tf.multiply(as_float, 2)
    return tf.subtract(doubled, 1)
output = step(tf.matmul(train_in, w))
error = tf.subtract(train_out, output)
mse = tf.reduce_mean(tf.square(error))
delta = tf.matmul(train_in, error, transpose_a=True)
train = tf.compat.v1.assign(w, tf.add(w, delta))
sess = tf.compat.v1.Session()
sess.run(tf.compat.v1.global_variables_initializer())
err, target = 1.0, 0.0
epoch, max_epochs = 0, 10
while err > target and epoch < max_epochs:
    epoch += 1
    err, _ = sess.run([mse, train])
    print('epoch:', epoch, 'mse:', err, 'output:', output)

In [1]:
import numpy as np

In [10]:
k = np.concatenate((np.ones(1).T,np.array((2,3))))

In [11]:
np.dot(k,0.4)

array([0.4, 0.8, 1.2])