# Truth Table Neural Net

In [155]:
## Import package

import tensorflow as tf

In [156]:
## Define data

x = [[False,False],[False,True],[True,False],[True,True]]
y = [False,True,True,False]

In [157]:
## OHE the data

x = tf.keras.utils.to_categorical(x, num_classes=2)
print(x_OHE,'\n')
y = tf.keras.utils.to_categorical(y, num_classes=2)
print(y_OHE)

tf.Tensor(
[[[1. 0.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [0. 1.]]], shape=(4, 2, 2), dtype=float32) 

tf.Tensor(
[[1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]], shape=(4, 2), dtype=float32)


In [158]:
## Define model

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(10, input_shape=(2,2), activation='relu'))
model.add(tf.keras.layers.Dense(4, activation='relu'))
model.add(tf.keras.layers.Dense(1, activation = 'sigmoid'))

sgd = tf.keras.optimizers.SGD(lr=0.0001)

## Compile model with metrics
model.compile(optimizer=sgd, loss='binary_crossentropy', metrics=['accuracy'])
model.summary()


Model: "sequential_30"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_74 (Dense)             (None, 2, 10)             30        
_________________________________________________________________
dense_75 (Dense)             (None, 2, 4)              44        
_________________________________________________________________
dense_76 (Dense)             (None, 2, 1)              5         
Total params: 79
Trainable params: 79
Non-trainable params: 0
_________________________________________________________________


In [171]:
%%capture

## Train the model
hist = model.fit(x,y, epochs=500, verbose=2)

In [177]:
print("Loss:\n", hist.history['loss'][-1])
print("Accuracy:\n", hist.history['accuracy'][-1])
print("\nPrediction:\n",model.predict(x))
print("\nClasses:\n",model.predict_classes(x)[:,1])

Loss:
 0.6934748888015747
Accuracy:
 0.5

Prediction:
 [[[0.48190063]
  [0.48190063]]

 [[0.48190063]
  [0.5003518 ]]

 [[0.5003518 ]
  [0.48190063]]

 [[0.5003518 ]
  [0.5003518 ]]]

Classes:
 [[0]
 [1]
 [0]
 [1]]
